name: 📦 Build & Publish NuGet Package

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔧 Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Change this if using a different .NET version

      - name: 📦 Restore Dependencies
        run: dotnet restore

      - name: 🏗 Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: 📦 Pack BlobSyncer NuGet Package
        run: dotnet pack src/BlobSyncer.Azure.BlobStorage/BlobSyncer.Azure.BlobStorage.csproj --configuration Release --output ./artifacts --property:PackageId=BlobSyncer

      # - name: 📦 Pack BlobSyncer.AmazonS3 NuGet Package
      #   run: dotnet pack src/BlobSyncer.Amazon.S3/BlobSyncer.Amazon.S3.csproj --configuration Release --output ./artifacts --property:PackageId=BlobSyncer.AmazonS3

      # - name: 📦 Pack BlobSyncer.AISearch NuGet Package
      #   run: dotnet pack src/BlobSyncer.Azure.AISearch/BlobSyncer.Azure.AISearch.csproj --configuration Release --output ./artifacts --property:PackageId=BlobSyncer.AISearch

      - name: 📂 Upload NuGet Package as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts/*.nupkg

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'

    steps:
      - name: 📥 Download NuGet Package
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts

      - name: 🚀 Publish NuGet Package
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
